version: '3' 

services: 
    postgres:
      image: postgres
      container_name: postgres
      ports:
        - 5432:5432
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      volumes:
        - pgdata:/var/lib/postgresql/data
    redis:  
      image: redis
      container_name: cache
      ports:
        - 6379:6379
      volumes:
        - redisdata:/data
    frontend:  
      image: onefive
      build: ../../Part 1/1.5/frontend-example-docker
      container_name: frontend
      ports:
        - 5000:5000
      environment:
        - API_URL=http://localhost:8000
    backend:  
      image: onesix
      build: ../../Part 1/1.6/backend-example-docker
      volumes: 
        - ./logs.txt:/mydir/logs.txt
      links:
        - redis
        - postgres
      container_name: backend
      ports:
        - 8000:8000
      environment:
        - FRONT_URL=http://localhost:5000
        - REDIS=redis
        - DB_USERNAME=postgres
        - DB_PASSWORD=postgres
        - DB_NAME=postgres
        - DB_HOST=postgres
volumes:
   pgdata:
   redisdata:
